### ISSUE TITLE
CLI client 

### ISSUE THREAD

**Issue by Fl1tzi** [theRealCarneiro/pulsemeeter#20]
# TODO:

- [x] simple cli client
### create complete cli client
- [x] make arguments work again, etc...
- [x] parsing ([library](https://docs.python.org/3/library/argparse.html#sub-commands))
- [x] fix mute not using bool right
- [x] add descriptions to commands
- [x] better naming (eg. --connect hi2 b1)
- [x] ?? only connect to server when command is executed
- [ ] finding bugs and removing them

**reference:**
#17 - Socket
#15 - Command Line?
